'use client';

import React, { createContext, useContext, useState, useEffect, ReactNode } from 'react';

type LanguageContextType = {
  language: string;
  changeLanguage: (lang: string) => void;
  t: (key: string, params?: Record<string, any>) => string;
};

// Varsayılan değerler
const defaultContext: LanguageContextType = {
  language: 'tr',
  changeLanguage: () => {},
  t: (key: string, params?: Record<string, any>) => key,
};

// Çeviriler
const translations: Record<string, Record<string, string>> = {
  tr: {
    // Genel
    'app.title': 'AI Sohbet Botu',
    'app.description': 'Yapay zeka destekli sohbet botu platformu',
    'app.welcome': 'Hoş Geldiniz',
    
    // Navigasyon
    'nav.dashboard': 'Gösterge Paneli',
    'nav.bots': 'Botlarım',
    'nav.chats': 'Sohbetler',
    'nav.settings': 'Ayarlar',
    'nav.logout': 'Çıkış Yap',
    
    // Dashboard
    'dashboard.overview': 'Genel Bakış',
    'dashboard.my_chatbots': 'Chatbotlarım',
    'dashboard.conversations': 'Konuşmalar',
    'dashboard.analytics': 'Analitikler',
    'dashboard.visitors': 'Ziyaretçiler', 
    'dashboard.billing': 'Faturalama',
    'dashboard.settings': 'Ayarlar',
    'dashboard.free_plan': 'Ücretsiz Plan',
    'dashboard.upgrade_info': 'Daha fazla özelliğe erişmek için planınızı yükseltin.',
    'dashboard.upgrade_button': 'Premium\'a Yükselt',
    'dashboard.notifications': 'Bildirimler',
    'dashboard.view_all_notifications': 'Tüm bildirimleri görüntüle',
    'dashboard.profile': 'Profil',
    'dashboard.my_bots': 'Botlarım',
    'dashboard.create_bot': 'Yeni Bot Oluştur',
    'dashboard.recent_conversations': 'Son Konuşmalar',
    'dashboard.view_all': 'Tümünü Görüntüle',
    'dashboard.active_visitors': 'Aktif Ziyaretçiler',
    'dashboard.total_bots': 'Toplam Bot',
    'dashboard.total_conversations': 'Toplam Konuşma',
    'dashboard.total_messages': 'Toplam Mesaj',
    'dashboard.bot_status_online': 'Çevrimiçi',
    'dashboard.bot_status_offline': 'Çevrimdışı',
    'dashboard.bot_status_maintenance': 'Bakımda',
    'dashboard.last_activity': 'Son Aktivite',
    'dashboard.conversations_stat': 'Konuşma',
    'dashboard.conversion_rate': 'Dönüşüm Oranı',
    'dashboard.view_details': 'Detayları Görüntüle',
    'dashboard.no_bots': 'Henüz bir bot oluşturmadınız.',
    'dashboard.create_first_bot': 'İlk botunuzu oluşturun',
    'dashboard.today': 'Bugün',
    'dashboard.yesterday': 'Dün',
    'dashboard.days_ago': '{0} gün önce',
    'dashboard.minutes_ago': '{0} dakika önce',
    'dashboard.hours_ago': '{0} saat önce',
    'dashboard.unknown_date': 'Bilinmiyor',
    'dashboard.now': 'Şimdi',
    'dashboard.hello': 'Merhaba',
    'dashboard.panel_description': 'Panel istatistiklerinize ve chatbotlarınıza genel bakış.',
    'dashboard.edit': 'Düzenle',
    'dashboard.view': 'Görüntüle',
    'dashboard.no_conversations': 'Henüz Konuşma Yok',
    'dashboard.no_conversations_description': 'Botlarınızla konuşmalar başladığında burada görünecekler.',
    'dashboard.conversation_not_found': 'Konuşma Bulunamadı',
    'dashboard.refresh': 'Yenile',
    'dashboard.export': 'Dışa Aktar',
    'dashboard.loading': 'Yükleniyor...',
    'dashboard.success_rate': 'Başarı Oranı',
    'dashboard.anonymous_user': 'Anonim Kullanıcı',
    'dashboard.no_message': 'Mesaj yok',
    
    // Botlar Sayfası
    'bots.manage_description': 'Tüm chatbotlarınızı yönetin ve performanslarını izleyin',
    'bots.search_placeholder': 'Bot ara...',
    'bots.status_filter': 'Durum Filtresi',
    'bots.all_bots': 'Tümü',
    'bots.online': 'Aktif',
    'bots.offline': 'Devre Dışı',
    'bots.design_custom_bot': 'Özel bir chatbot tasarlayın',
    'bots.conversations': 'Konuşmalar',
    'bots.success_rate': 'Başarı Oranı',
    'bots.last_activity': 'Son aktivite',
    'bots.edit': 'Düzenle',
    'bots.view': 'Görüntüle',
    'bots.create_new': 'Yeni Bot Oluştur',
    'bots.delete': 'Botu Sil',
    'bots.delete_confirm': 'Bu botu silmek istediğinizden emin misiniz?',
    'bots.delete_success': 'Bot başarıyla silindi',
    'bots.delete_error': 'Bot silinirken bir hata oluştu',
    'bots.clone': 'Klonla',
    'bots.status_change': 'Durumu Değiştir',
    'bots.status_online': 'Çevrimiçi',
    'bots.status_offline': 'Çevrimdışı',
    'bots.status_maintenance': 'Bakımda',
    'bots.drag_to_reorder': 'Sıralamak için sürükleyin',
    'bots.pin': 'Sabitle',
    'bots.unpin': 'Sabitlemeyi Kaldır',
    'bots.update_success': 'Bot başarıyla güncellendi',
    'bots.update_error': 'Bot güncellenirken bir hata oluştu',
    
    // Konuşmalar Sayfası
    'conversations.title': 'Konuşmalarım',
    'conversations.description': 'Botlarınızla yapılan tüm kullanıcı konuşmalarını görüntüleyin ve yönetin',
    'conversations.resetFilters': 'Filtreleri Sıfırla',
    'conversations.search.placeholder': 'Konuşmalarda ara...',
    'conversations.confirm.delete': 'Bu konuşmayı silmek istediğinizden emin misiniz?',
    'conversations.error.loading': 'Konuşmalar yüklenirken bir hata oluştu',
    'conversations.error.deleting': 'Konuşma silinirken bir hata oluştu',
    'conversations.success.deleted': 'Konuşma başarıyla silindi',
    'conversations.empty.title': 'Hiç Konuşma Yok',
    'conversations.empty.description': 'Kullanıcılarınız botlarınızla konuştukça burada listelenecektir',
    'conversations.sortBy.placeholder': 'Sıralama',
    'conversations.sortBy.lastMessage': 'Son mesaj',
    'conversations.sortBy.startDate': 'Başlangıç tarihi',
    'conversations.sortBy.messageCount': 'Mesaj sayısı',
    'conversations.sortBy.duration': 'Süre',
    'conversations.filter.timeFrame': 'Zaman aralığı',
    'conversations.filter.allTime': 'Tüm zamanlar',
    'conversations.filter.today': 'Bugün',
    'conversations.filter.yesterday': 'Dün',
    'conversations.filter.lastWeek': 'Son hafta',
    'conversations.filter.lastMonth': 'Son ay',
    'conversations.filter.bot': 'Bot',
    'conversations.filter.allBots': 'Tüm botlar',
    'conversations.filter.status': 'Durum',
    'conversations.filter.allStatuses': 'Tüm durumlar',
    'conversations.filter.satisfaction': 'Memnuniyet',
    'conversations.filter.allRatings': 'Tüm değerlendirmeler',
    'conversations.status.completed': 'Tamamlandı',
    'conversations.status.ongoing': 'Devam Ediyor',
    'conversations.status.abandoned': 'Yarıda Kaldı',
    'conversations.satisfaction.positive': 'Olumlu',
    'conversations.satisfaction.neutral': 'Nötr',
    'conversations.satisfaction.negative': 'Olumsuz',
    'conversations.success.resolved': 'Başarıyla çözüldü',
    'conversations.success.unresolved': 'Çözülemedi',
    'conversations.messageCount': '{{count}} mesaj',
    'conversations.duration': '{{minutes}} dk {{seconds}} sn',
    'conversations.pagination': '{{total}} konuşmadan {{start}}-{{end}} arası',
    
    // Analitikler Sayfası
    'analytics.title': 'Analitikler',
    'analytics.description': 'Chatbot sisteminin performansı ve kullanıcı etkileşimleri',
    'analytics.weekly': 'Haftalık',
    'analytics.monthly': 'Aylık',
    'analytics.yearly': 'Yıllık',
    'analytics.refresh': 'Yenile',
    'analytics.totalConversations': 'Toplam Konuşma',
    'analytics.totalMessages': 'Toplam Mesaj',
    'analytics.avgSessionTime': 'Ortalama Oturum Süresi',
    'analytics.successRate': 'Başarı Oranı',
    'analytics.comparedToLastMonth': 'geçen aya göre',
    'analytics.fifteenDaysAgo': '15 gün önce',
    'analytics.today': 'Bugün',
    'analytics.hourlyActivity': 'Saatlik Aktivite',
    'analytics.topBots': 'En İyi Chatbotlar',
    'analytics.topQuestions': 'En Çok Sorulan Sorular',
    'analytics.dataLoadError': 'Veriler Yüklenemedi',
    'analytics.dataLoadErrorDescription': 'Veriler yüklenirken bir hata oluştu. Lütfen daha sonra tekrar deneyin.',
    'analytics.tryAgain': 'Yeniden Dene',
    'analytics.noData': 'Veri Yok',
    'analytics.noDataDescription': 'Henüz analiz edilecek veri bulunmuyor',
    'analytics.conversations': 'Konuşma',
    'analytics.bot': 'Bot',
    'analytics.avg': 'Ort',
    
    // Ziyaretçiler Sayfası
    'visitors.title': 'Ziyaretçiler',
    'visitors.description': 'Web sitesi ziyaretçileri ve etkileşim analizleri',
    'visitors.exportData': 'Verileri Dışa Aktar',
    'visitors.stats.totalVisitors': 'Toplam Ziyaretçiler',
    'visitors.stats.newVisitors': 'Yeni Ziyaretçiler',
    'visitors.stats.totalVisits': 'Toplam Ziyaretler',
    'visitors.stats.conversionRate': 'Dönüşüm Oranı',
    'visitors.stats.fromLastMonth': 'geçen aya göre',
    'visitors.stats.fromLastWeek': 'geçen haftaya göre',
    'visitors.stats.today': 'bugün',
    'visitors.stats.improvement': 'iyileşme',
    'visitors.search.placeholder': 'Ziyaretçi ara (IP, ülke, şehir, tarayıcı, OS...)',
    'visitors.filter.timeFrame': 'Zaman aralığı',
    'visitors.filter.allTime': 'Tüm zamanlar',
    'visitors.filter.today': 'Bugün',
    'visitors.filter.lastWeek': 'Son 7 gün',
    'visitors.filter.lastMonth': 'Son 30 gün',
    'visitors.filter.source': 'Kaynak',
    'visitors.filter.allSources': 'Tüm kaynaklar',
    'visitors.filter.deviceType': 'Cihaz Türü',
    'visitors.filter.allDevices': 'Tüm cihazlar',
    'visitors.source.direct': 'Doğrudan',
    'visitors.source.organic': 'Organik',
    'visitors.source.referral': 'Yönlendirme',
    'visitors.source.social': 'Sosyal Medya',
    'visitors.source.email': 'E-posta',
    'visitors.deviceType.desktop': 'Masaüstü',
    'visitors.deviceType.mobile': 'Mobil',
    'visitors.deviceType.tablet': 'Tablet',
    'visitors.firstVisit': 'İlk Ziyaret',
    'visitors.lastVisit': 'Son Ziyaret',
    'visitors.visits': 'Ziyaretler',
    'visitors.conversations': 'Konuşmalar',
    'visitors.timeSpent.label': 'Geçirilen Süre',
    'visitors.timeSpent.minutes': '{{minutes}} dk',
    'visitors.timeSpent.hoursMinutes': '{{hours}} sa {{minutes}} dk',
    'visitors.visitorList': 'Ziyaretçi Listesi',
    'visitors.view.grid': 'Izgara',
    'visitors.view.list': 'Liste',
    'visitors.empty.title': 'Henüz Ziyaretçi Yok',
    'visitors.empty.description': 'Web sitenizi ziyaret eden kullanıcılar burada görüntülenecektir',
    'visitors.activeUsersLast24Hours': 'Son 24 saatteki aktif kullanıcı sayısı',
    
    // Faturalama Sayfası
    'billing.title': 'Faturalama',
    'billing.description': 'Abonelik planınızı yönetin ve fatura geçmişinizi görüntüleyin',
    'billing.current_plan': 'Mevcut Plan',
    'billing.upgrade': 'Yükselt',
    'billing.downgrade': 'Düşür',
    'billing.cancel': 'İptal Et',
    'billing.renews_on': 'Yenileme tarihi',
    'billing.payment_method': 'Ödeme Yöntemi',
    'billing.update_payment': 'Ödeme Yöntemini Güncelle',
    'billing.invoices': 'Faturalar',
    'billing.no_invoices': 'Henüz fatura bulunmamaktadır',
    'billing.date': 'Tarih',
    'billing.amount': 'Tutar',
    'billing.status': 'Durum',
    'billing.download': 'İndir',
    'billing.usage': 'Kullanım',
    'billing.messages_used': 'Kullanılan Mesaj',
    'billing.bots_created': 'Oluşturulan Bot',
    'billing.storage_used': 'Kullanılan Depolama',
    'billing.plan_free': 'Ücretsiz Plan',
    'billing.plan_basic': 'Temel Plan',
    'billing.plan_pro': 'Pro Plan',
    'billing.plan_enterprise': 'Kurumsal Plan',
    'billing.monthly': 'Aylık',
    'billing.yearly': 'Yıllık',
    'billing.save_with_yearly': 'Yıllık planla %20 tasarruf edin',
    'billing.free_trial': 'Ücretsiz Deneme',
    'billing.starts_at': 'Başlangıç fiyatı',
    
    // Ayarlar
    'settings.title': 'Uygulama Ayarları',
    'settings.description': 'Uygulama deneyiminizi kişiselleştirin ve tercihlerinizi yönetin',
    'settings.language': 'Dil',
    'settings.language.description': 'Arayüzün dilini değiştirin',
    'settings.notifications': 'Bildirimler',
    'settings.notifications.description': 'Hangi bildirimleri almak istediğinizi yapılandırın',
    'settings.privacy': 'Gizlilik',
    'settings.privacy.description': 'Gizlilik ve veri işleme tercihlerinizi yönetin',
    'settings.sessions': 'Oturumlar',
    'settings.sessions.description': 'Oturum süresi ve otomatik çıkış ayarlarınızı yönetin',
    'settings.delete': 'Hesabı Sil',
    'settings.delete.description': 'Hesabınızı ve ilişkili tüm verileri kalıcı olarak silin',
    'settings.info': 'Bilgisi',
    'settings.save': 'Tüm Ayarları Kaydet',
    'settings.changes': 'Kaydedilmemiş değişiklikler var',
    'settings.language.current': 'Şu an seçili dil: Türkçe',
    
    // Oturumlar
    'sessions.autologout': 'Otomatik Çıkış Süresi',
    'sessions.autologout.description': 'Belirli bir hareketsizlik süresi sonrasında',
    'sessions.timeout': 'Oturum Sona Erme Süresi',
    'sessions.timeout.description': 'Yeniden giriş yapmak zorunda kalmadan önce',
    'sessions.never': 'Asla',
    'sessions.minutes': '{0} dakika',
    'sessions.hour': '1 saat', 
    'sessions.hours': '{0} saat',
    'sessions.day': '1 gün',
    'sessions.week': '1 hafta',
    'sessions.month': '30 gün',
    
    // Hesap Silme
    'delete.warning': 'Dikkat: Bu işlem geri alınamaz',
    'delete.when': 'Hesabınızı sildiğinizde:',
    'delete.data1': 'Tüm kişisel bilgileriniz silinecek',
    'delete.data2': 'Oluşturduğunuz tüm sohbetler ve mesajlar silinecek',
    'delete.data3': 'Tüm botlarınız ve yapılandırmalarınız silinecek',
    'delete.data4': 'Kaydedilen tüm ayarlarınız silinecek',
    'delete.data5': 'Bu işlem geri alınamaz ve verileriniz kurtarılamaz',
    'delete.confirm.title': 'İşlemi Onaylayın',
    'delete.confirm.message': 'Hesabınızı silmeden önce, bu işlemin geri alınamayacağını anladığınızı onaylayın.',
    'delete.confirm.checkbox': 'Hesabımı silmenin geri alınamaz olduğunu anlıyorum ve onaylıyorum',
    'delete.button': 'Hesabımı Kalıcı Olarak Sil',
    'delete.cancel': 'İptal Et ve Ayarlara Dön',
    
    // Bildirimler
    'notifications.browser': 'Tarayıcı Bildirimleri',
    'notifications.browser.description': 'Uygulamada olmadığınızda tarayıcı bildirimlerini alın',
    'notifications.email': 'E-posta Bildirimleri',
    'notifications.email.description': 'Önemli olaylarla ilgili e-posta bildirimleri alın',
    'notifications.marketing': 'Pazarlama E-postaları',
    'notifications.marketing.description': 'Promosyonlar ve özel teklifler hakkında e-postalar alın',
    'notifications.newsletter': 'Aylık Bülten',
    'notifications.newsletter.description': 'Aylık ürün güncellemeleri ve haberler',
    'notifications.chatbot': 'Chatbot Güncellemeleri',
    'notifications.chatbot.description': 'Chatbotlarınızdaki önemli olaylar hakkında bildirimler',
    
    // Gizlilik
    'privacy.analytics': 'Analitik Verisi Toplama',
    'privacy.analytics.description': 'Uygulamayı geliştirmek için anonim kullanım verilerinin toplanmasına izin verin',
    'privacy.usage': 'Kullanım Verilerini Paylaşma',
    'privacy.usage.description': 'Geliştiricilere kullanım verilerinin paylaşılmasına izin verin',
    'privacy.cookies': 'Çerez Tercihleri',
    'privacy.cookies.necessary': 'Sadece Gerekli',
    'privacy.cookies.necessary.description': 'Yalnızca web sitesinin çalışması için gerekli olan çerezleri kabul edin',
    'privacy.cookies.functional': 'Fonksiyonel',
    'privacy.cookies.functional.description': 'Tercihlerinizi hatırlamak için fonksiyonel çerezleri kabul edin',
    'privacy.cookies.all': 'Tümü',
    'privacy.cookies.all.description': 'Tüm çerezleri kabul edin, analitik ve pazarlama dahil',
    
    // Butonlar
    'button.save': 'Kaydet',
    'button.cancel': 'İptal',
    'button.confirm': 'Onayla',
    'button.delete': 'Sil',
    'button.back': 'Geri',
    
    // Mesajlar
    'message.saved': 'Başarıyla kaydedildi',
    'message.error': 'Bir hata oluştu',
    'message.confirm': 'Bu işlemi yapmak istediğinizden emin misiniz?',
    
    // Ortak
    'common.search': 'Ara',
    'common.searching': 'Aranıyor',
    'common.clear': 'Temizle',
    'common.filters': 'Filtreler',
    
    // Konuşmalar Sayfası
    'conversations.filter_hide': 'Filtreleri Gizle',
    'conversations.filter_show': 'Filtreleri Göster',
    'conversations.list_title': 'Konuşma Listesi',
    'conversations.count': '{{count}} konuşma',
    'conversations.not_found': 'Konuşma Bulunamadı',
    'conversations.not_found_description': 'Arama sonuçlarına uygun konuşma bulunamadı. Filtreleri değiştirmeyi deneyin.',
    'conversations.clear_filters': 'Filtreleri Temizle',
    'conversations.view': 'Görüntüle',
    'conversations.delete': 'Sil',
  },
  en: {
    // General
    'app.title': 'AI Chat Bot',
    'app.description': 'Artificial intelligence powered chat bot platform',
    'app.welcome': 'Welcome',
    
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.bots': 'My Bots',
    'nav.chats': 'Conversations',
    'nav.settings': 'Settings',
    'nav.logout': 'Logout',
    
    // Dashboard
    'dashboard.overview': 'Overview',
    'dashboard.my_chatbots': 'My Chatbots',
    'dashboard.conversations': 'Conversations',
    'dashboard.analytics': 'Analytics',
    'dashboard.visitors': 'Visitors', 
    'dashboard.billing': 'Billing',
    'dashboard.settings': 'Settings',
    'dashboard.free_plan': 'Free Plan',
    'dashboard.upgrade_info': 'Upgrade your plan to access more features.',
    'dashboard.upgrade_button': 'Upgrade to Premium',
    'dashboard.notifications': 'Notifications',
    'dashboard.view_all_notifications': 'View all notifications',
    'dashboard.profile': 'Profile',
    'dashboard.my_bots': 'My Bots',
    'dashboard.create_bot': 'Create New Bot',
    'dashboard.recent_conversations': 'Recent Conversations',
    'dashboard.view_all': 'View All',
    'dashboard.active_visitors': 'Active Visitors',
    'dashboard.total_bots': 'Total Bots',
    'dashboard.total_conversations': 'Total Conversations',
    'dashboard.total_messages': 'Total Messages',
    'dashboard.bot_status_online': 'Online',
    'dashboard.bot_status_offline': 'Offline',
    'dashboard.bot_status_maintenance': 'Maintenance',
    'dashboard.last_activity': 'Last Activity',
    'dashboard.conversations_stat': 'Conversations',
    'dashboard.conversion_rate': 'Conversion Rate',
    'dashboard.view_details': 'View Details',
    'dashboard.no_bots': 'You haven\'t created any bots yet.',
    'dashboard.create_first_bot': 'Create your first bot',
    'dashboard.today': 'Today',
    'dashboard.yesterday': 'Yesterday',
    'dashboard.days_ago': '{0} days ago',
    'dashboard.minutes_ago': '{0} minutes ago',
    'dashboard.hours_ago': '{0} hours ago',
    'dashboard.unknown_date': 'Unknown',
    'dashboard.now': 'Now',
    'dashboard.hello': 'Hello',
    'dashboard.panel_description': 'Overview of your dashboard statistics and chatbots.',
    'dashboard.edit': 'Edit',
    'dashboard.view': 'View',
    'dashboard.no_conversations': 'No Conversations Yet',
    'dashboard.no_conversations_description': 'Conversations with your bots will appear here when they start.',
    'dashboard.conversation_not_found': 'Conversation Not Found',
    'dashboard.refresh': 'Refresh',
    'dashboard.export': 'Export',
    'dashboard.loading': 'Loading...',
    'dashboard.success_rate': 'Success Rate',
    'dashboard.anonymous_user': 'Anonymous User',
    'dashboard.no_message': 'No message',
    
    // Bots Page
    'bots.manage_description': 'Manage all your chatbots and monitor their performance',
    'bots.search_placeholder': 'Search bots...',
    'bots.status_filter': 'Status Filter',
    'bots.all_bots': 'All',
    'bots.online': 'Online',
    'bots.offline': 'Offline',
    'bots.design_custom_bot': 'Design a custom chatbot',
    'bots.conversations': 'Conversations',
    'bots.success_rate': 'Success Rate',
    'bots.last_activity': 'Last activity',
    'bots.edit': 'Edit',
    'bots.view': 'View',
    'bots.create_new': 'Create New Bot',
    'bots.delete': 'Delete Bot',
    'bots.delete_confirm': 'Are you sure you want to delete this bot?',
    'bots.delete_success': 'Bot deleted successfully',
    'bots.delete_error': 'An error occurred while deleting the bot',
    'bots.clone': 'Clone',
    'bots.status_change': 'Change Status',
    'bots.status_online': 'Online',
    'bots.status_offline': 'Offline',
    'bots.status_maintenance': 'Maintenance',
    'bots.drag_to_reorder': 'Drag to reorder',
    'bots.pin': 'Pin',
    'bots.unpin': 'Unpin',
    'bots.update_success': 'Bot updated successfully',
    'bots.update_error': 'An error occurred while updating the bot',
    
    // Conversations Page
    'conversations.title': 'My Conversations',
    'conversations.description': 'View and manage all user conversations with your bots',
    'conversations.resetFilters': 'Reset Filters',
    'conversations.search.placeholder': 'Search conversations...',
    'conversations.confirm.delete': 'Are you sure you want to delete this conversation?',
    'conversations.error.loading': 'An error occurred while loading conversations',
    'conversations.error.deleting': 'An error occurred while deleting the conversation',
    'conversations.success.deleted': 'Conversation successfully deleted',
    'conversations.empty.title': 'No Conversations',
    'conversations.empty.description': 'As your users chat with your bots, they will be listed here',
    'conversations.sortBy.placeholder': 'Sort by',
    'conversations.sortBy.lastMessage': 'Last message',
    'conversations.sortBy.startDate': 'Start date',
    'conversations.sortBy.messageCount': 'Message count',
    'conversations.sortBy.duration': 'Duration',
    'conversations.filter.timeFrame': 'Time frame',
    'conversations.filter.allTime': 'All time',
    'conversations.filter.today': 'Today',
    'conversations.filter.yesterday': 'Yesterday',
    'conversations.filter.lastWeek': 'Last week',
    'conversations.filter.lastMonth': 'Last month',
    'conversations.filter.bot': 'Bot',
    'conversations.filter.allBots': 'All bots',
    'conversations.filter.status': 'Status',
    'conversations.filter.allStatuses': 'All statuses',
    'conversations.filter.satisfaction': 'Satisfaction',
    'conversations.filter.allRatings': 'All ratings',
    'conversations.status.completed': 'Completed',
    'conversations.status.ongoing': 'Ongoing',
    'conversations.status.abandoned': 'Abandoned',
    'conversations.satisfaction.positive': 'Positive',
    'conversations.satisfaction.neutral': 'Neutral',
    'conversations.satisfaction.negative': 'Negative',
    'conversations.success.resolved': 'Successfully resolved',
    'conversations.success.unresolved': 'Unresolved',
    'conversations.messageCount': '{{count}} messages',
    'conversations.duration': '{{minutes}}m {{seconds}}s',
    'conversations.pagination': '{{start}}-{{end}} of {{total}} conversations',
    
    // Analytics Page
    'analytics.title': 'Analytics',
    'analytics.description': 'Performance and user interactions of the chatbot system',
    'analytics.weekly': 'Weekly',
    'analytics.monthly': 'Monthly',
    'analytics.yearly': 'Yearly',
    'analytics.refresh': 'Refresh',
    'analytics.totalConversations': 'Total Conversations',
    'analytics.totalMessages': 'Total Messages',
    'analytics.avgSessionTime': 'Average Session Time',
    'analytics.successRate': 'Success Rate',
    'analytics.comparedToLastMonth': 'compared to last month',
    'analytics.fifteenDaysAgo': '15 days ago',
    'analytics.today': 'Today',
    'analytics.hourlyActivity': 'Hourly Activity',
    'analytics.topBots': 'Top Chatbots',
    'analytics.topQuestions': 'Top Questions',
    'analytics.dataLoadError': 'Failed to Load Data',
    'analytics.dataLoadErrorDescription': 'An error occurred while loading data. Please try again later.',
    'analytics.tryAgain': 'Try Again',
    'analytics.noData': 'No Data',
    'analytics.noDataDescription': 'No data available for analysis yet',
    'analytics.conversations': 'Conversations',
    'analytics.bot': 'Bot',
    'analytics.avg': 'Avg',
    
    // Visitors Page
    'visitors.title': 'Visitors',
    'visitors.description': 'Website visitors and interaction analytics',
    'visitors.exportData': 'Export Data',
    'visitors.stats.totalVisitors': 'Total Visitors',
    'visitors.stats.newVisitors': 'New Visitors',
    'visitors.stats.totalVisits': 'Total Visits',
    'visitors.stats.conversionRate': 'Conversion Rate',
    'visitors.stats.fromLastMonth': 'from last month',
    'visitors.stats.fromLastWeek': 'from last week',
    'visitors.stats.today': 'today',
    'visitors.stats.improvement': 'improvement',
    'visitors.search.placeholder': 'Search visitors (IP, country, city, browser, OS...)',
    'visitors.filter.timeFrame': 'Time frame',
    'visitors.filter.allTime': 'All time',
    'visitors.filter.today': 'Today',
    'visitors.filter.lastWeek': 'Last 7 days',
    'visitors.filter.lastMonth': 'Last 30 days',
    'visitors.filter.source': 'Source',
    'visitors.filter.allSources': 'All sources',
    'visitors.filter.deviceType': 'Device Type',
    'visitors.filter.allDevices': 'All devices',
    'visitors.source.direct': 'Direct',
    'visitors.source.organic': 'Organic',
    'visitors.source.referral': 'Referral',
    'visitors.source.social': 'Social Media',
    'visitors.source.email': 'Email',
    'visitors.deviceType.desktop': 'Desktop',
    'visitors.deviceType.mobile': 'Mobile',
    'visitors.deviceType.tablet': 'Tablet',
    'visitors.firstVisit': 'First Visit',
    'visitors.lastVisit': 'Last Visit',
    'visitors.visits': 'Visits',
    'visitors.conversations': 'Conversations',
    'visitors.timeSpent.label': 'Time Spent',
    'visitors.timeSpent.minutes': '{{minutes}}m',
    'visitors.timeSpent.hoursMinutes': '{{hours}}h {{minutes}}m',
    'visitors.visitorList': 'Visitor List',
    'visitors.view.grid': 'Grid',
    'visitors.view.list': 'List',
    'visitors.empty.title': 'No Visitors Yet',
    'visitors.empty.description': 'Users visiting your website will be displayed here',
    'visitors.activeUsersLast24Hours': 'Active users in the last 24 hours',
    
    // Billing Page
    'billing.title': 'Billing',
    'billing.description': 'Manage your subscription plan and view billing history',
    'billing.current_plan': 'Current Plan',
    'billing.upgrade': 'Upgrade',
    'billing.downgrade': 'Downgrade',
    'billing.cancel': 'Cancel',
    'billing.renews_on': 'Renews on',
    'billing.payment_method': 'Payment Method',
    'billing.update_payment': 'Update Payment Method',
    'billing.invoices': 'Invoices',
    'billing.no_invoices': 'No invoices yet',
    'billing.date': 'Date',
    'billing.amount': 'Amount',
    'billing.status': 'Status',
    'billing.download': 'Download',
    'billing.usage': 'Usage',
    'billing.messages_used': 'Messages Used',
    'billing.bots_created': 'Bots Created',
    'billing.storage_used': 'Storage Used',
    'billing.plan_free': 'Free Plan',
    'billing.plan_basic': 'Basic Plan',
    'billing.plan_pro': 'Pro Plan',
    'billing.plan_enterprise': 'Enterprise Plan',
    'billing.monthly': 'Monthly',
    'billing.yearly': 'Yearly',
    'billing.save_with_yearly': 'Save 20% with yearly plan',
    'billing.free_trial': 'Free Trial',
    'billing.starts_at': 'Starts at',
    
    // Settings
    'settings.title': 'Application Settings',
    'settings.description': 'Customize your application experience and manage your preferences',
    'settings.language': 'Language',
    'settings.language.description': 'Change the interface language',
    'settings.notifications': 'Notifications',
    'settings.notifications.description': 'Configure which notifications you want to receive',
    'settings.privacy': 'Privacy',
    'settings.privacy.description': 'Manage your privacy and data processing preferences',
    'settings.sessions': 'Sessions',
    'settings.sessions.description': 'Manage your session duration and automatic logout settings',
    'settings.delete': 'Delete Account',
    'settings.delete.description': 'Permanently delete your account and all associated data',
    'settings.info': 'Information',
    'settings.save': 'Save All Settings',
    'settings.changes': 'You have unsaved changes',
    'settings.language.current': 'Currently selected language: English',
    
    // Sessions
    'sessions.autologout': 'Auto Logout Time',
    'sessions.autologout.description': 'After a specific period of inactivity',
    'sessions.timeout': 'Session Expiry Time',
    'sessions.timeout.description': 'Before having to log in again',
    'sessions.never': 'Never',
    'sessions.minutes': '{0} minutes',
    'sessions.hour': '1 hour',
    'sessions.hours': '{0} hours',
    'sessions.day': '1 day',
    'sessions.week': '1 week',
    'sessions.month': '30 days',
    
    // Account Deletion
    'delete.warning': 'Warning: This action cannot be undone',
    'delete.when': 'When you delete your account:',
    'delete.data1': 'All your personal information will be deleted',
    'delete.data2': 'All conversations and messages you created will be deleted',
    'delete.data3': 'All your bots and configurations will be deleted',
    'delete.data4': 'All your saved settings will be deleted',
    'delete.data5': 'This action cannot be undone and your data cannot be recovered',
    'delete.confirm.title': 'Confirm Action',
    'delete.confirm.message': 'Before deleting your account, please confirm that you understand this action cannot be undone.',
    'delete.confirm.checkbox': 'I understand and confirm that deleting my account cannot be undone',
    'delete.button': 'Permanently Delete My Account',
    'delete.cancel': 'Cancel and Return to Settings',
    
    // Notifications
    'notifications.browser': 'Browser Notifications',
    'notifications.browser.description': 'Receive browser notifications when you are not in the app',
    'notifications.email': 'Email Notifications',
    'notifications.email.description': 'Receive email notifications about important events',
    'notifications.marketing': 'Marketing Emails',
    'notifications.marketing.description': 'Receive emails about promotions and special offers',
    'notifications.newsletter': 'Monthly Newsletter',
    'notifications.newsletter.description': 'Monthly product updates and news',
    'notifications.chatbot': 'Chatbot Updates',
    'notifications.chatbot.description': 'Notifications about important events in your chatbots',
    
    // Privacy
    'privacy.analytics': 'Collect Analytics Data',
    'privacy.analytics.description': 'Allow collection of anonymous usage data to improve the app',
    'privacy.usage': 'Share Usage Data',
    'privacy.usage.description': 'Allow sharing of usage data with developers',
    'privacy.cookies': 'Cookie Preferences',
    'privacy.cookies.necessary': 'Necessary Only',
    'privacy.cookies.necessary.description': 'Accept only cookies necessary for the website to function',
    'privacy.cookies.functional': 'Functional',
    'privacy.cookies.functional.description': 'Accept functional cookies to remember your preferences',
    'privacy.cookies.all': 'All',
    'privacy.cookies.all.description': 'Accept all cookies, including analytics and marketing',
    
    // Buttons
    'button.save': 'Save',
    'button.cancel': 'Cancel',
    'button.confirm': 'Confirm',
    'button.delete': 'Delete',
    'button.back': 'Back',
    
    // Messages
    'message.saved': 'Successfully saved',
    'message.error': 'An error occurred',
    'message.confirm': 'Are you sure you want to do this?',
    
    // Ortak
    'common.search': 'Search',
    'common.searching': 'Searching',
    'common.clear': 'Clear',
    'common.filters': 'Filters',
    
    // Konuşmalar Sayfası
    'conversations.filter_hide': 'Hide Filters',
    'conversations.filter_show': 'Show Filters',
    'conversations.list_title': 'Conversation List',
    'conversations.count': '{{count}} conversations',
    'conversations.not_found': 'No Conversations Found',
    'conversations.not_found_description': 'No conversations match your search criteria. Try changing the filters.',
    'conversations.clear_filters': 'Clear Filters',
    'conversations.view': 'View',
    'conversations.delete': 'Delete',
  }
};

// Context oluştur
const LanguageContext = createContext<LanguageContextType>(defaultContext);

// Context kullanım hook'u
export const useLanguage = () => useContext(LanguageContext);

// Context provider bileşeni
export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<string>('tr'); // Varsayılan dil: Türkçe

  // Sayfa yüklendiğinde localStorage'dan dil tercihini al
  useEffect(() => {
    const savedLanguage = localStorage.getItem('appLanguage');
    if (savedLanguage && (savedLanguage === 'tr' || savedLanguage === 'en')) {
      setLanguage(savedLanguage);
    }
  }, []);

  // Dil değiştirme fonksiyonu
  const changeLanguage = (lang: string) => {
    if (lang === 'tr' || lang === 'en') {
      setLanguage(lang);
      localStorage.setItem('appLanguage', lang);
      document.documentElement.lang = lang;
      
      // Dil değişikliğini diğer pencere/sekmelere bildirmek için özel bir olay tetikle
      const event = new StorageEvent('storage', {
        key: 'appLanguage',
        newValue: lang,
        storageArea: localStorage
      });
      window.dispatchEvent(event);
    }
  };

  // Çeviri fonksiyonu
  const t = (key: string, params?: Record<string, any>): string => {
    let translation = translations[language]?.[key] || key;
    
    // Parametreleri çeviriye yerleştir
    if (params) {
      Object.keys(params).forEach(param => {
        const regex = new RegExp(`{{${param}}}`, 'g');
        translation = translation.replace(regex, params[param]);
      });
    }
    
    return translation;
  };

  return (
    <LanguageContext.Provider value={{ language, changeLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export default LanguageProvider; 